# Generated by Django 2.2.4 on 2019-08-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_musicfileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfileinfo',
            name='musiccategory',
            field=models.CharField(blank=True, choices=[('自然', '1'), ('動物', '2'), ('人', '3'), ('室內', '4'), ('旋律', '5'), ('技術', '5')], max_length=6),
        ),
    ]
