# Generated by Django 2.2.4 on 2019-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_musicfileinfo_musiccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfileinfo',
            name='music_pic',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicfileinfo',
            name='music_tag',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicfileinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musicfileinfo',
            name='musiccategory',
            field=models.CharField(blank=True, choices=[('nature', '自然'), ('animal', '動物'), ('person', '人'), ('indoor', '室內'), ('melody', '旋律'), ('technical', '技術')], max_length=12),
        ),
    ]
