# Generated by Django 2.2.4 on 2019-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_auto_20190826_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_user_click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=200)),
                ('musicid', models.IntegerField(max_length=120)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musicfileinfo',
            name='music_pic',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='musicfileinfo',
            name='music_tag',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='musicfileinfo',
            name='musiccategory',
            field=models.CharField(choices=[('自然', '自然'), ('動物', '動物'), ('人', '人'), ('室內', '室內'), ('旋律', '旋律'), ('技術', '技術')], max_length=12),
        ),
    ]
